FROM mhart/alpine-node:11.1.0 

WORKDIR /app

EXPOSE 4200

RUN npm install -g @angular/cli@7.0.4

CMD ["/bin/sh"]

#docker build --rm -f Dockerfile  -t angular-cli-docker:7.0.4 .
#docker run -i -t angular-cli-docker:7.0.4 /bin/sh

